import fs from "fs";
import path from "path";

// 1 - 150 items with rich TOEIC metadata
const chunk1Data = [
  {
    word: "abide by",
    partOfSpeech: "verb",
    meaningVi: "tuân theo",
    meaningEn: "To accept and act in accordance with a rule or agreement",
    pronunciation: "/əˈbaɪd baɪ/",
    exampleSentence: "Both parties agreed to abide by the terms of the signed contract.",
    exampleTranslation: "Cả hai bên đã đồng ý tuân theo các điều khoản của hợp đồng đã ký.",
    difficulty: "INTERMEDIATE",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "abide by a contract, abide by rules",
    notes: "Rất hay gặp trong Part 5 & 7 chủ đề hợp đồng."
  },
  {
    word: "ability",
    partOfSpeech: "noun",
    meaningVi: "khả năng",
    meaningEn: "Possession of the means or skill to do something",
    pronunciation: "/əˈbɪləti/",
    exampleSentence: "Her ability to resolve client disputes quickly impressed the management.",
    exampleTranslation: "Khả năng giải quyết tranh chấp với khách hàng nhanh chóng của cô ấy đã gây ấn tượng với ban quản lý.",
    difficulty: "BEGINNER",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 6",
    collocations: "demonstrate ability, leadership ability",
    notes: "Đi với giới từ: ability to do something."
  },
  {
    word: "abundant",
    partOfSpeech: "adjective",
    meaningVi: "thừa mứa",
    meaningEn: "Existing or available in large quantities; plentiful",
    pronunciation: "/əˈbʌndənt/",
    exampleSentence: "The warehouse has an abundant supply of electronic components for the new model.",
    exampleTranslation: "Nhà kho có nguồn cung thừa mứa các linh kiện điện tử cho mẫu sản phẩm mới.",
    difficulty: "INTERMEDIATE",
    topic: "Manufacturing",
    toeicParts: "Part 5, Part 7",
    collocations: "abundant supply, abundant resources",
    notes: "Từ đồng nghĩa: plentiful, ample."
  },
  {
    word: "accept",
    partOfSpeech: "verb",
    meaningVi: "chấp nhận",
    meaningEn: "To consent to receive or undertake something offered",
    pronunciation: "/əkˈsept/",
    exampleSentence: "The candidate decided to accept the job offer after reviewing the salary package.",
    exampleTranslation: "Ứng viên đã quyết định chấp nhận lời mời nhận việc sau khi xem xét chế độ lương thưởng.",
    difficulty: "BEGINNER",
    topic: "Recruitment",
    toeicParts: "Part 5, Part 7",
    collocations: "accept an offer, accept terms",
    notes: "Phân biệt với 'except' (ngoại trừ)."
  },
  {
    word: "access",
    partOfSpeech: "noun",
    meaningVi: "truy cập",
    meaningEn: "The means or opportunity to approach or enter a place or system",
    pronunciation: "/ˈækses/",
    exampleSentence: "Only authorized personnel have access to the confidential client database.",
    exampleTranslation: "Chỉ nhân viên được ủy quyền mới có quyền truy cập vào cơ sở dữ liệu khách hàng bảo mật.",
    difficulty: "BEGINNER",
    topic: "Technology",
    toeicParts: "Part 5, Part 6",
    collocations: "gain access to, unauthorized access",
    notes: "Vừa là danh từ vừa là động từ (access the files)."
  },
  {
    word: "accommodate",
    partOfSpeech: "verb",
    meaningVi: "cung cấp",
    meaningEn: "To provide lodging or sufficient space for; to fit or adapt",
    pronunciation: "/əˈkɒmədeɪt/",
    exampleSentence: "The conference hall can accommodate up to five hundred attendees comfortably.",
    exampleTranslation: "Hội trường hội nghị có thể cung cấp đủ chỗ cho tối đa năm trăm người tham dự.",
    difficulty: "INTERMEDIATE",
    topic: "Hotels",
    toeicParts: "Part 5, Part 7",
    collocations: "accommodate guests, accommodate needs",
    notes: "Hay ra trong đề thi Part 7 chủ đề khách sạn/sự kiện."
  },
  {
    word: "accomplishment",
    partOfSpeech: "noun",
    meaningVi: "sự hoàn thành",
    meaningEn: "Something that has been achieved successfully",
    pronunciation: "/əˈkʌmplɪʃmənt/",
    exampleSentence: "Completing the software upgrade ahead of schedule was a major accomplishment.",
    exampleTranslation: "Hoàn thành việc nâng cấp phần mềm trước thời hạn là một sự hoàn thành xuất sắc.",
    difficulty: "INTERMEDIATE",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 7",
    collocations: "great accomplishment, sense of accomplishment",
    notes: "Đồng nghĩa: achievement, success."
  },
  {
    word: "accounting",
    partOfSpeech: "noun",
    meaningVi: "tính toán, kế toán",
    meaningEn: "The process or work of keeping financial accounts",
    pronunciation: "/əˈkaʊntɪŋ/",
    exampleSentence: "The accounting department will issue the revised financial report by Friday.",
    exampleTranslation: "Phòng kế toán sẽ phát hành báo cáo tài chính sửa đổi trước thứ Sáu.",
    difficulty: "BEGINNER",
    topic: "Finance",
    toeicParts: "Part 5, Part 7",
    collocations: "accounting department, accounting records",
    notes: "Xuất hiện liên tục trong bài đọc báo cáo tài chính."
  },
  {
    word: "accumulate",
    partOfSpeech: "verb",
    meaningVi: "sự tích lũy",
    meaningEn: "To gather together or acquire an increasing number or quantity of",
    pronunciation: "/əˈkjuːmjəleɪt/",
    exampleSentence: "Employees accumulate paid vacation days with each month of service.",
    exampleTranslation: "Nhân viên tích lũy số ngày nghỉ phép có lương theo từng tháng làm việc.",
    difficulty: "INTERMEDIATE",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 6",
    collocations: "accumulate points, accumulate wealth",
    notes: "Danh từ tương ứng: accumulation."
  },
  {
    word: "accurately",
    partOfSpeech: "adverb",
    meaningVi: "chính xác",
    meaningEn: "In a way that is correct, exact, and without errors",
    pronunciation: "/ˈækjərətli/",
    exampleSentence: "The accountant accurately calculated the quarterly tax obligations.",
    exampleTranslation: "Kế toán viên đã tính toán chính xác các nghĩa vụ thuế theo quý.",
    difficulty: "INTERMEDIATE",
    topic: "Finance",
    toeicParts: "Part 5, Part 6",
    collocations: "predict accurately, measure accurately",
    notes: "Tính từ: accurate; danh từ: accuracy."
  },
  {
    word: "accustom to",
    partOfSpeech: "phrase",
    meaningVi: "quen với",
    meaningEn: "To become familiar with something through practice or habit",
    pronunciation: "/əˈkʌstəm tuː/",
    exampleSentence: "New staff members quickly accustom to the company's communication tools.",
    exampleTranslation: "Các nhân viên mới nhanh chóng quen với các công cụ giao tiếp của công ty.",
    difficulty: "INTERMEDIATE",
    topic: "Office",
    toeicParts: "Part 5, Part 6",
    collocations: "be accustomed to V-ing, accustom oneself to",
    notes: "Cấu trúc 'be accustomed to + V-ing' cực kỳ phổ biến trong Part 5."
  },
  {
    word: "achievement",
    partOfSpeech: "noun",
    meaningVi: "sự đạt được",
    meaningEn: "A thing done successfully, typically by effort, courage, or skill",
    pronunciation: "/əˈtʃiːvmənt/",
    exampleSentence: "The CEO praised the sales team for their outstanding quarterly achievement.",
    exampleTranslation: "Tổng giám đốc đã khen ngợi đội ngũ bán hàng vì thành tích đạt được xuất sắc trong quý.",
    difficulty: "BEGINNER",
    topic: "Sales",
    toeicParts: "Part 5, Part 7",
    collocations: "remarkable achievement, lifetime achievement",
    notes: "Động từ: achieve."
  },
  {
    word: "acquire",
    partOfSpeech: "verb",
    meaningVi: "đạt được",
    meaningEn: "To buy or obtain an asset or object; to learn or develop a skill",
    pronunciation: "/əˈkwaɪər/",
    exampleSentence: "Our corporation plans to acquire a regional logistics firm next quarter.",
    exampleTranslation: "Tập đoàn của chúng tôi dự định mua lại/đạt được một công ty logistics khu vực vào quý tới.",
    difficulty: "INTERMEDIATE",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "acquire a company, acquire knowledge",
    notes: "Thuật ngữ M&A: Mergers and Acquisitions (Mua bán và sáp nhập)."
  },
  {
    word: "action",
    partOfSpeech: "noun",
    meaningVi: "hành động",
    meaningEn: "The fact or process of doing something, typically to achieve an aim",
    pronunciation: "/ˈækʃn/",
    exampleSentence: "Immediate action is required to resolve the shipping delay issue.",
    exampleTranslation: "Cần có hành động ngay lập tức để giải quyết vấn đề chậm trễ giao hàng.",
    difficulty: "BEGINNER",
    topic: "Customer Service",
    toeicParts: "Part 5, Part 7",
    collocations: "take action, plan of action",
    notes: "Cụm 'take immediate action' rất thường gặp."
  },
  {
    word: "address",
    partOfSpeech: "verb",
    meaningVi: "hướng đến",
    meaningEn: "To think about and begin to deal with an issue or problem",
    pronunciation: "/əˈdres/",
    exampleSentence: "The upcoming seminar will address common challenges in project management.",
    exampleTranslation: "Hội thảo sắp tới sẽ hướng đến và giải quyết các thách thức phổ biến trong quản lý dự án.",
    difficulty: "INTERMEDIATE",
    topic: "Meetings",
    toeicParts: "Part 5, Part 7",
    collocations: "address an issue, address concerns",
    notes: "Trong TOEIC, 'address' thường mang nghĩa giải quyết vấn đề hơn là địa chỉ."
  },
  {
    word: "adhere to",
    partOfSpeech: "phrase",
    meaningVi: "tuân theo",
    meaningEn: "To stick firmly or follow closely a rule, guideline, or agreement",
    pronunciation: "/ədˈhɪər tuː/",
    exampleSentence: "Factory workers must adhere to strict safety protocols at all times.",
    exampleTranslation: "Công nhân nhà máy phải tuân theo các quy định an toàn nghiêm ngặt vào mọi thời điểm.",
    difficulty: "INTERMEDIATE",
    topic: "Manufacturing",
    toeicParts: "Part 5, Part 6",
    collocations: "adhere to standards, adhere to policies",
    notes: "Đồng nghĩa: abide by, comply with, conform to."
  },
  {
    word: "adjacent",
    partOfSpeech: "adjective",
    meaningVi: "kế bên",
    meaningEn: "Next to or adjoining something else",
    pronunciation: "/əˈdʒeɪsnt/",
    exampleSentence: "The cafeteria is located in the building adjacent to our main office.",
    exampleTranslation: "Nhà ăn nằm trong tòa nhà kế bên văn phòng chính của chúng tôi.",
    difficulty: "INTERMEDIATE",
    topic: "Office",
    toeicParts: "Part 1, Part 5",
    collocations: "adjacent to, adjacent building",
    notes: "Thường đi kèm giới từ 'to': adjacent to."
  },
  {
    word: "adjustment",
    partOfSpeech: "noun",
    meaningVi: "sự điều chỉnh",
    meaningEn: "A small alteration or movement made to achieve a desired result",
    pronunciation: "/əˈdʒʌstmənt/",
    exampleSentence: "We made a minor adjustment to the production schedule to avoid overtime.",
    exampleTranslation: "Chúng tôi đã thực hiện một sự điều chỉnh nhỏ trong lịch trình sản xuất để tránh tăng ca.",
    difficulty: "INTERMEDIATE",
    topic: "Manufacturing",
    toeicParts: "Part 5, Part 7",
    collocations: "make an adjustment, price adjustment",
    notes: "Động từ: adjust."
  },
  {
    word: "admire",
    partOfSpeech: "verb",
    meaningVi: "ngưỡng mộ",
    meaningEn: "To regard with respect or warm approval",
    pronunciation: "/ədˈmaɪər/",
    exampleSentence: "Colleagues admire his dedication and exceptional problem-solving skills.",
    exampleTranslation: "Các đồng nghiệp ngưỡng mộ sự cống hiến và kỹ năng giải quyết vấn đề xuất sắc của anh ấy.",
    difficulty: "BEGINNER",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 7",
    collocations: "admire someone for, deeply admire",
    notes: "Tính từ: admirable (đáng ngưỡng mộ)."
  },
  {
    word: "admit",
    partOfSpeech: "verb",
    meaningVi: "cho phép",
    meaningEn: "To allow someone to enter a place or to confess to be true",
    pronunciation: "/ədˈmɪt/",
    exampleSentence: "This visitor badge will admit you to all technical exhibition zones.",
    exampleTranslation: "Thẻ khách này sẽ cho phép bạn vào tất cả các khu vực triển lãm kỹ thuật.",
    difficulty: "INTERMEDIATE",
    topic: "Events",
    toeicParts: "Part 5, Part 7",
    collocations: "admit to, admit visitors",
    notes: "Danh từ: admission (sự vào cửa, vé vào cửa)."
  },
  {
    word: "advanced",
    partOfSpeech: "adjective",
    meaningVi: "cao hơn",
    meaningEn: "Far on or ahead in development or progress; modern and sophisticated",
    pronunciation: "/ədˈvɑːnst/",
    exampleSentence: "The laboratory purchased advanced analytical equipment for medical research.",
    exampleTranslation: "Phòng thí nghiệm đã mua các thiết bị phân tích ở mức cao hơn, tiên tiến cho nghiên cứu y tế.",
    difficulty: "INTERMEDIATE",
    topic: "Technology",
    toeicParts: "Part 5, Part 7",
    collocations: "advanced technology, advanced level",
    notes: "Hay gặp trong mô tả sản phẩm công nghệ (advanced features)."
  },
  {
    word: "affordable",
    partOfSpeech: "adjective",
    meaningVi: "có khả năng",
    meaningEn: "Inexpensive; reasonably priced so people have enough money to buy",
    pronunciation: "/əˈfɔːdəbl/",
    exampleSentence: "The company offers affordable health insurance options for all full-time workers.",
    exampleTranslation: "Công ty cung cấp các gói bảo hiểm sức khỏe có khả năng chi trả cho tất cả nhân viên chính thức.",
    difficulty: "BEGINNER",
    topic: "Health",
    toeicParts: "Part 5, Part 7",
    collocations: "affordable prices, affordable rates",
    notes: "Động từ: afford; đồng nghĩa: reasonable, cost-effective."
  },
  {
    word: "agenda",
    partOfSpeech: "noun",
    meaningVi: "lịch trình thảo luận",
    meaningEn: "A list of items to be discussed at a formal meeting",
    pronunciation: "/əˈdʒendə/",
    exampleSentence: "The chairperson sent the meeting agenda to all board members in advance.",
    exampleTranslation: "Chủ tọa đã gửi lịch trình thảo luận cuộc họp trước cho tất cả các thành viên hội đồng.",
    difficulty: "BEGINNER",
    topic: "Meetings",
    toeicParts: "Part 5, Part 7",
    collocations: "meeting agenda, on the agenda",
    notes: "Cực kỳ phổ biến trong email và biên bản cuộc họp Part 7."
  },
  {
    word: "agent",
    partOfSpeech: "noun",
    meaningVi: "đại diện của công ty",
    meaningEn: "A person who acts on behalf of another person or group",
    pronunciation: "/ˈeɪdʒənt/",
    exampleSentence: "Please contact our travel agent to confirm your flight reservations.",
    exampleTranslation: "Vui lòng liên hệ với đại diện/đại lý du lịch của chúng tôi để xác nhận đặt chỗ chuyến bay.",
    difficulty: "BEGINNER",
    topic: "Travel",
    toeicParts: "Part 3, Part 5",
    collocations: "travel agent, sales agent, real estate agent",
    notes: "Danh từ chỉ nơi chốn/tổ chức: agency."
  },
  {
    word: "aggressively",
    partOfSpeech: "adverb",
    meaningVi: "xông xáo, tháo vát",
    meaningEn: "In a determined, forceful, and competitive manner",
    pronunciation: "/əˈɡresɪvli/",
    exampleSentence: "The startup aggressively marketed its new payment platform across Asia.",
    exampleTranslation: "Công ty khởi nghiệp đã tiếp thị xông xáo nền tảng thanh toán mới của mình khắp châu Á.",
    difficulty: "ADVANCED",
    topic: "Marketing",
    toeicParts: "Part 5, Part 6",
    collocations: "market aggressively, pursue aggressively",
    notes: "Trong kinh doanh, 'aggressive' mang nghĩa năng động, quyết liệt cạnh tranh."
  },
  {
    word: "agreement",
    partOfSpeech: "noun",
    meaningVi: "thỏa thuận",
    meaningEn: "A negotiated and typically legally binding arrangement between parties",
    pronunciation: "/əˈɡriːmənt/",
    exampleSentence: "Both directors signed a partnership agreement after weeks of negotiation.",
    exampleTranslation: "Cả hai giám đốc đã ký thỏa thuận hợp tác sau nhiều tuần đàm phán.",
    difficulty: "BEGINNER",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "reach an agreement, sign an agreement",
    notes: "Động từ: agree."
  },
  {
    word: "allocate",
    partOfSpeech: "verb",
    meaningVi: "phân vùng",
    meaningEn: "To distribute resources or duties for a particular purpose",
    pronunciation: "/ˈæləkeɪt/",
    exampleSentence: "The committee will allocate additional funds to the research division.",
    exampleTranslation: "Ủy ban sẽ phân bổ/phân vùng thêm ngân sách cho bộ phận nghiên cứu.",
    difficulty: "ADVANCED",
    topic: "Finance",
    toeicParts: "Part 5, Part 7",
    collocations: "allocate funds, allocate budget",
    notes: "Danh từ: allocation."
  },
  {
    word: "allow",
    partOfSpeech: "verb",
    meaningVi: "cho phép",
    meaningEn: "To give someone permission to do something; permit",
    pronunciation: "/əˈlaʊ/",
    exampleSentence: "The new policy does not allow employees to carry personal laptops into the server room.",
    exampleTranslation: "Chính sách mới không cho phép nhân viên mang laptop cá nhân vào phòng máy chủ.",
    difficulty: "BEGINNER",
    topic: "Technology",
    toeicParts: "Part 5, Part 6",
    collocations: "allow someone to do something, allow for",
    notes: "Cấu trúc: allow somebody to do something."
  },
  {
    word: "alternative",
    partOfSpeech: "noun",
    meaningVi: "lựa chọn khác",
    meaningEn: "One of two or more available possibilities",
    pronunciation: "/ɔːlˈtɜːnətɪv/",
    exampleSentence: "Taking the express train is a faster alternative to driving during rush hour.",
    exampleTranslation: "Đi tàu tốc hành là một lựa chọn khác nhanh hơn so với tự lái xe vào giờ cao điểm.",
    difficulty: "INTERMEDIATE",
    topic: "Transportation",
    toeicParts: "Part 5, Part 7",
    collocations: "viable alternative, alternative route",
    notes: "Cũng dùng như tính từ: alternative energy (năng lượng thay thế)."
  },
  {
    word: "announcement",
    partOfSpeech: "noun",
    meaningVi: "tuyên bố công khai",
    meaningEn: "A public or formal statement about a fact, occurrence, or intention",
    pronunciation: "/əˈnaʊnsmənt/",
    exampleSentence: "The CEO made an announcement regarding the company's upcoming expansion.",
    exampleTranslation: "Tổng giám đốc đã đưa ra một tuyên bố công khai liên quan đến kế hoạch mở rộng sắp tới.",
    difficulty: "BEGINNER",
    topic: "Business",
    toeicParts: "Part 4, Part 7",
    collocations: "make an announcement, public announcement",
    notes: "Động từ: announce; thường xuất hiện trong Part 4 (Short Talks)."
  },
  {
    word: "annually",
    partOfSpeech: "adverb",
    meaningVi: "hằng năm",
    meaningEn: "Once every year; yearly",
    pronunciation: "/ˈænjuəli/",
    exampleSentence: "Performance reviews are conducted annually in December for all staff.",
    exampleTranslation: "Các đánh giá hiệu suất được tiến hành hằng năm vào tháng 12 cho toàn thể nhân viên.",
    difficulty: "BEGINNER",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 6",
    collocations: "held annually, meet annually",
    notes: "Tính từ: annual (annual report, annual meeting)."
  },
  {
    word: "anxious",
    partOfSpeech: "adjective",
    meaningVi: "lo lắng",
    meaningEn: "Experiencing worry, unease, or nervousness",
    pronunciation: "/ˈæŋkʃəs/",
    exampleSentence: "Investors were anxious about the sudden currency fluctuations in the market.",
    exampleTranslation: "Các nhà đầu tư đã lo lắng về sự biến động tiền tệ bất ngờ trên thị trường.",
    difficulty: "INTERMEDIATE",
    topic: "Finance",
    toeicParts: "Part 5, Part 7",
    collocations: "anxious about, anxious to do something",
    notes: "Danh từ: anxiety."
  },
  {
    word: "appeal",
    partOfSpeech: "verb",
    meaningVi: "thu hút",
    meaningEn: "To be attractive or interesting to someone",
    pronunciation: "/əˈpiːl/",
    exampleSentence: "The minimalist design of the new smartphone appeals to young professionals.",
    exampleTranslation: "Thiết kế tối giản của điện thoại mới thu hút các chuyên gia trẻ tuổi.",
    difficulty: "INTERMEDIATE",
    topic: "Marketing",
    toeicParts: "Part 5, Part 7",
    collocations: "appeal to customers, broad appeal",
    notes: "Cấu trúc: appeal to somebody."
  },
  {
    word: "apply",
    partOfSpeech: "verb",
    meaningVi: "áp dụng",
    meaningEn: "To put into operation or use; to make a formal request",
    pronunciation: "/əˈplaɪ/",
    exampleSentence: "We must apply the latest quality assurance techniques to our production line.",
    exampleTranslation: "Chúng ta phải áp dụng các kỹ thuật đảm bảo chất lượng mới nhất vào dây chuyền sản xuất.",
    difficulty: "BEGINNER",
    topic: "Manufacturing",
    toeicParts: "Part 5, Part 7",
    collocations: "apply for a job, apply a rule",
    notes: "Apply for (nộp đơn xin việc), apply to (áp dụng cho)."
  },
  {
    word: "appointment",
    partOfSpeech: "noun",
    meaningVi: "cuộc hẹn",
    meaningEn: "An arrangement to meet someone at a particular time and place",
    pronunciation: "/əˈpɔɪntmənt/",
    exampleSentence: "Mr. Davis scheduled an appointment with the prospective buyer for 2 PM.",
    exampleTranslation: "Ông Davis đã lên lịch một cuộc hẹn với người mua tiềm năng vào lúc 2 giờ chiều.",
    difficulty: "BEGINNER",
    topic: "Meetings",
    toeicParts: "Part 3, Part 7",
    collocations: "make an appointment, cancel an appointment",
    notes: "Cũng có nghĩa là sự bổ nhiệm chức vụ (appointment to the board)."
  },
  {
    word: "appreciation",
    partOfSpeech: "noun",
    meaningVi: "sự nâng giá trị",
    meaningEn: "Recognition and enjoyment of the good qualities of someone or something; increase in value",
    pronunciation: "/əˌpriːʃiˈeɪʃn/",
    exampleSentence: "The company gave bonuses in appreciation of the employees' hard work.",
    exampleTranslation: "Công ty đã trao tiền thưởng để thể hiện sự cảm kích/nâng giá trị công sức của nhân viên.",
    difficulty: "INTERMEDIATE",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 7",
    collocations: "in appreciation of, show appreciation",
    notes: "Động từ: appreciate; trong tài chính còn nghĩa là tăng giá trị."
  },
  {
    word: "apprehensive",
    partOfSpeech: "adjective",
    meaningVi: "lo lắng về tương lai",
    meaningEn: "Anxious or fearful that something bad or unpleasant will happen",
    pronunciation: "/ˌæprɪˈhensɪv/",
    exampleSentence: "Staff members felt apprehensive about the proposed corporate restructuring.",
    exampleTranslation: "Các nhân viên cảm thấy lo lắng về tương lai khi nghe về đề xuất tái cấu trúc doanh nghiệp.",
    difficulty: "ADVANCED",
    topic: "Human Resources",
    toeicParts: "Part 5, Part 7",
    collocations: "apprehensive about, apprehensive of",
    notes: "Thường đi kèm giới từ 'about'."
  },
  {
    word: "apprentice",
    partOfSpeech: "noun",
    meaningVi: "sinh viên (ẩm thực)",
    meaningEn: "A person learning a trade from a skilled employer",
    pronunciation: "/əˈprentɪs/",
    exampleSentence: "The head chef trained the apprentice in preparing traditional pastry dishes.",
    exampleTranslation: "Bếp trưởng đã đào tạo sinh viên học việc ngành ẩm thực cách chuẩn bị các món bánh truyền thống.",
    difficulty: "INTERMEDIATE",
    topic: "Restaurants",
    toeicParts: "Part 5, Part 7",
    collocations: "trade apprentice, apprentice training",
    notes: "Danh từ: apprenticeship (thời gian học nghề)."
  },
  {
    word: "approach",
    partOfSpeech: "noun",
    meaningVi: "tiếp cận",
    meaningEn: "A way of dealing with a situation or problem",
    pronunciation: "/əˈprəʊtʃ/",
    exampleSentence: "Our consulting team took an innovative approach to reducing supply chain costs.",
    exampleTranslation: "Đội ngũ tư vấn của chúng tôi đã thực hiện một cách tiếp cận đổi mới để giảm chi phí chuỗi cung ứng.",
    difficulty: "INTERMEDIATE",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "new approach, approach to a problem",
    notes: "Vừa là danh từ vừa là động từ (approach the deadline)."
  },
  {
    word: "arrangement",
    partOfSpeech: "noun",
    meaningVi: "sự sắp xếp",
    meaningEn: "A plan or preparation for a future event or journey",
    pronunciation: "/əˈreɪndʒmənt/",
    exampleSentence: "Travel arrangements for the overseas delegates have already been finalized.",
    exampleTranslation: "Sự sắp xếp chuyến đi cho các đại biểu nước ngoài đã được hoàn tất.",
    difficulty: "BEGINNER",
    topic: "Travel",
    toeicParts: "Part 3, Part 7",
    collocations: "make arrangements, travel arrangements",
    notes: "Động từ: arrange."
  },
  {
    word: "arrive",
    partOfSpeech: "verb",
    meaningVi: "đến",
    meaningEn: "To reach a destination at the end of a journey or stage",
    pronunciation: "/əˈraɪv/",
    exampleSentence: "The shipment of raw materials is expected to arrive at the harbor tomorrow morning.",
    exampleTranslation: "Lô hàng nguyên liệu thô dự kiến sẽ đến cảng vào sáng mai.",
    difficulty: "BEGINNER",
    topic: "Transportation",
    toeicParts: "Part 1, Part 5",
    collocations: "arrive on time, arrive at the station",
    notes: "Danh từ: arrival."
  },
  {
    word: "as needed",
    partOfSpeech: "phrase",
    meaningVi: "cần",
    meaningEn: "Whenever necessary or required",
    pronunciation: "/æz ˈniːdɪd/",
    exampleSentence: "Technical support specialists are dispatched to branch offices as needed.",
    exampleTranslation: "Các chuyên viên hỗ trợ kỹ thuật được điều động đến các văn phòng chi nhánh khi cần.",
    difficulty: "BEGINNER",
    topic: "Customer Service",
    toeicParts: "Part 5, Part 7",
    collocations: "use as needed, adjust as needed",
    notes: "Cụm trạng từ thông dụng chỉ mức độ cần thiết."
  },
  {
    word: "ascertain",
    partOfSpeech: "verb",
    meaningVi: "để chắc chắn xem",
    meaningEn: "To find out or learn with certainty",
    pronunciation: "/ˌæsəˈteɪn/",
    exampleSentence: "The audit was conducted to ascertain whether internal accounting rules were obeyed.",
    exampleTranslation: "Cuộc kiểm toán được thực hiện để chắc chắn xem các quy tắc kế toán nội bộ có được tuân thủ hay không.",
    difficulty: "ADVANCED",
    topic: "Finance",
    toeicParts: "Part 5, Part 7",
    collocations: "ascertain whether, ascertain the cause",
    notes: "Từ vựng trang trọng thường gặp trong Part 7."
  },
  {
    word: "aspect",
    partOfSpeech: "noun",
    meaningVi: "khía cạnh",
    meaningEn: "A particular part or feature of something",
    pronunciation: "/ˈæspekt/",
    exampleSentence: "Customer feedback highlights every positive aspect of our delivery service.",
    exampleTranslation: "Phản hồi của khách hàng làm nổi bật mọi khía cạnh tích cực trong dịch vụ giao hàng của chúng tôi.",
    difficulty: "INTERMEDIATE",
    topic: "Customer Service",
    toeicParts: "Part 5, Part 7",
    collocations: "key aspect, every aspect",
    notes: "Số nhiều: aspects."
  },
  {
    word: "assemble",
    partOfSpeech: "verb",
    meaningVi: "tập hợp lại",
    meaningEn: "To gather together in one place; to fit together the component parts of",
    pronunciation: "/əˈsembl/",
    exampleSentence: "Technicians assemble each smartphone unit in a dust-free clean room.",
    exampleTranslation: "Các kỹ thuật viên tập hợp và lắp ráp từng chiếc điện thoại thông minh trong phòng sạch không bụi.",
    difficulty: "INTERMEDIATE",
    topic: "Manufacturing",
    toeicParts: "Part 1, Part 5",
    collocations: "assemble parts, assemble in the auditorium",
    notes: "Danh từ: assembly (assembly line - dây chuyền lắp ráp)."
  },
  {
    word: "assess",
    partOfSpeech: "verb",
    meaningVi: "đánh giá",
    meaningEn: "To evaluate or estimate the nature, quality, ability, or value of",
    pronunciation: "/əˈses/",
    exampleSentence: "The committee met to assess the economic viability of the proposed merger.",
    exampleTranslation: "Ủy ban đã họp để đánh giá tính khả thi kinh tế của đề xuất sáp nhập.",
    difficulty: "INTERMEDIATE",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "assess performance, assess the impact",
    notes: "Danh từ: assessment; đồng nghĩa: evaluate, judge."
  },
  {
    word: "asset",
    partOfSpeech: "noun",
    meaningVi: "tài sản",
    meaningEn: "A useful or valuable quality, person, or piece of property owned",
    pronunciation: "/ˈæset/",
    exampleSentence: "Her fluency in three languages is a tremendous asset to our international team.",
    exampleTranslation: "Sự thông thạo ba thứ tiếng của cô ấy là một tài sản to lớn đối với đội ngũ quốc tế của chúng tôi.",
    difficulty: "INTERMEDIATE",
    topic: "Finance",
    toeicParts: "Part 5, Part 7",
    collocations: "valuable asset, liquid assets",
    notes: "Trong bảng cân đối kế toán: Assets (Tài sản) = Liabilities + Equity."
  },
  {
    word: "assignment",
    partOfSpeech: "noun",
    meaningVi: "công việc được phân công",
    meaningEn: "A task or piece of work assigned to someone as part of a job or course of study",
    pronunciation: "/əˈsaɪnmənt/",
    exampleSentence: "He completed the research assignment two days before the project deadline.",
    exampleTranslation: "Anh ấy đã hoàn thành công việc được phân công hai ngày trước thời hạn của dự án.",
    difficulty: "BEGINNER",
    topic: "Office",
    toeicParts: "Part 5, Part 7",
    collocations: "complete an assignment, overseas assignment",
    notes: "Động từ: assign."
  },
  {
    word: "assist",
    partOfSpeech: "verb",
    meaningVi: "giúp đỡ",
    meaningEn: "To help someone, typically by doing a share of the work",
    pronunciation: "/əˈsɪst/",
    exampleSentence: "Customer representatives are ready to assist callers with order tracking.",
    exampleTranslation: "Đại diện khách hàng sẵn sàng giúp đỡ người gọi theo dõi đơn hàng.",
    difficulty: "BEGINNER",
    topic: "Customer Service",
    toeicParts: "Part 3, Part 5",
    collocations: "assist with, assist clients",
    notes: "Danh từ: assistance; người phụ tá: assistant."
  },
  {
    word: "association",
    partOfSpeech: "noun",
    meaningVi: "sự liên kết, hiệp hội",
    meaningEn: "An organized group of people who have the same interest or purpose",
    pronunciation: "/əˌsəʊsiˈeɪʃn/",
    exampleSentence: "Our firm joined the national trade association to expand its business network.",
    exampleTranslation: "Công ty chúng tôi đã gia nhập hiệp hội thương mại quốc gia để mở rộng mạng lưới kinh doanh.",
    difficulty: "INTERMEDIATE",
    topic: "Business",
    toeicParts: "Part 5, Part 7",
    collocations: "trade association, in association with",
    notes: "Động từ: associate."
  }
];

console.log(`Prepared sample 50 items. Let's write the full 150 items builder.`);
