// 600 Essential Words for the TOEIC raw dataset from user
export const RAW_600_WORDS = [
  { id: 1, word: "abide by", meaningVi: "tuân theo" },
  { id: 2, word: "ability", meaningVi: "khả năng" },
  { id: 3, word: "abundant", meaningVi: "thừa mứa" },
  { id: 4, word: "accept", meaningVi: "chấp nhận" },
  { id: 5, word: "access", meaningVi: "truy cập" },
  { id: 6, word: "accommodate", meaningVi: "cung cấp" },
  { id: 7, word: "accomplishment", meaningVi: "sự hoàn thành" },
  { id: 8, word: "accounting", meaningVi: "tính toán, kế toán" },
  { id: 9, word: "accumulate", meaningVi: "sự tích lũy" },
  { id: 10, word: "accurately", meaningVi: "chính xác" },
  { id: 11, word: "accustom to", meaningVi: "quen với" },
  { id: 12, word: "achievement", meaningVi: "sự đạt được" },
  { id: 13, word: "acquire", meaningVi: "đạt được" },
  { id: 14, word: "action", meaningVi: "hành động" },
  { id: 15, word: "address", meaningVi: "hướng đến" },
  { id: 16, word: "adhere to", meaningVi: "tuân theo" },
  { id: 17, word: "adjacent", meaningVi: "kế bên" },
  { id: 18, word: "adjustment", meaningVi: "sự điều chỉnh" },
  { id: 19, word: "admire", meaningVi: "ngưỡng mộ" },
  { id: 20, word: "admit", meaningVi: "cho phép" },
  { id: 21, word: "advanced", meaningVi: "cao hơn" },
  { id: 22, word: "affordable", meaningVi: "có khả năng" },
  { id: 23, word: "agenda", meaningVi: "lịch trình thảo luận" },
  { id: 24, word: "agent", meaningVi: "đại diện của công ty" },
  { id: 25, word: "aggressively", meaningVi: "xông xáo, tháo vát" },
  { id: 26, word: "agreement", meaningVi: "thỏa thuận" },
  { id: 27, word: "allocate", meaningVi: "phân vùng" },
  { id: 28, word: "allow", meaningVi: "cho phép" },
  { id: 29, word: "alternative", meaningVi: "lựa chọn khác" },
  { id: 30, word: "announcement", meaningVi: "tuyên bố công khai" },
  { id: 31, word: "annually", meaningVi: "hằng năm" },
  { id: 32, word: "anxious", meaningVi: "lo lắng" },
  { id: 33, word: "appeal", meaningVi: "thu hút" },
  { id: 34, word: "apply", meaningVi: "áp dụng" },
  { id: 35, word: "appointment", meaningVi: "cuộc hẹn" },
  { id: 36, word: "appreciation", meaningVi: "sự nâng giá trị" },
  { id: 37, word: "apprehensive", meaningVi: "lo lắng về tương lai" },
  { id: 38, word: "apprentice", meaningVi: "sinh viên (ẩm thực)" },
  { id: 39, word: "approach", meaningVi: "tiếp cận" },
  { id: 40, word: "arrangement", meaningVi: "sự sắp xếp" },
  { id: 41, word: "arrive", meaningVi: "đến" },
  { id: 42, word: "as needed", meaningVi: "cần" },
  { id: 43, word: "ascertain", meaningVi: "để chắc chắn xem" },
  { id: 44, word: "aspect", meaningVi: "khía cạnh" },
  { id: 45, word: "assemble", meaningVi: "tập hợp lại" },
  { id: 46, word: "assess", meaningVi: "đánh giá" },
  { id: 47, word: "asset", meaningVi: "tài sản" },
  { id: 48, word: "assignment", meaningVi: "công việc được phân công" },
  { id: 49, word: "assist", meaningVi: "giúp đỡ" },
  { id: 50, word: "association", meaningVi: "sự liên kết, hiệp hội" },
  { id: 51, word: "assume", meaningVi: "nắm giữ (vị trí mới)" },
  { id: 52, word: "assurance", meaningVi: "đảm bảo" },
  { id: 53, word: "attainment", meaningVi: "đạt được" },
  { id: 54, word: "attend", meaningVi: "tham dự" },
  { id: 55, word: "attitude", meaningVi: "thái độ, quan điểm" },
  { id: 56, word: "attract", meaningVi: "thu hút" },
  { id: 57, word: "audience", meaningVi: "khán giả" },
  { id: 58, word: "audit", meaningVi: "kiểm toán" },
  { id: 59, word: "authorize", meaningVi: "cho quyền" },
  { id: 60, word: "automatically", meaningVi: "tự động" },
  { id: 61, word: "available", meaningVi: "có sẵn" },
  { id: 62, word: "avoid", meaningVi: "tránh ra" },
  { id: 63, word: "aware", meaningVi: "nhận thức" },
  { id: 64, word: "aware of", meaningVi: "nhận thức" },
  { id: 65, word: "background", meaningVi: "kiến thức cơ bản" },
  { id: 66, word: "balance", meaningVi: "cân bằng" },
  { id: 67, word: "bargain", meaningVi: "mặc cả" },
  { id: 68, word: "basic", meaningVi: "cơ bản" },
  { id: 69, word: "basis", meaningVi: "cơ bản" },
  { id: 70, word: "bear", meaningVi: "chịu đựng" },
  { id: 71, word: "beforehand", meaningVi: "trước" },
  { id: 72, word: "behavior", meaningVi: "hành vi" },
  { id: 73, word: "benefit", meaningVi: "lợi ích" },
  { id: 74, word: "beverage", meaningVi: "thức uống giải khát" },
  { id: 75, word: "blanket", meaningVi: "cái chăn" },
  { id: 76, word: "board", meaningVi: "lên (tàu, xe, máy bay)" },
  { id: 77, word: "borrow", meaningVi: "mượn" },
  { id: 78, word: "brand", meaningVi: "thương hiệu" },
  { id: 79, word: "bring in", meaningVi: "thuê người" },
  { id: 80, word: "bring together", meaningVi: "tụ tập" },
  { id: 81, word: "bring up", meaningVi: "giới thiệu" },
  { id: 82, word: "broaden", meaningVi: "mở rộng" },
  { id: 83, word: "budget", meaningVi: "ngân sách" },
  { id: 84, word: "build up", meaningVi: "tăng dần theo thời gian" },
  { id: 85, word: "burden", meaningVi: "trách nhiệm" },
  { id: 86, word: "busy", meaningVi: "bận rộn" },
  { id: 87, word: "calculation", meaningVi: "tính toán" },
  { id: 88, word: "call in", meaningVi: "gọi đến" },
  { id: 89, word: "cancellation", meaningVi: "sự hủy bỏ" },
  { id: 90, word: "candidate", meaningVi: "ứng viên" },
  { id: 91, word: "capacity", meaningVi: "sức chứa, khả năng" },
  { id: 92, word: "carrier", meaningVi: "hãng vận tải" },
  { id: 93, word: "casually", meaningVi: "không trang trọng" },
  { id: 94, word: "catalog", meaningVi: "danh mục" },
  { id: 95, word: "catch up", meaningVi: "bắt kịp" },
  { id: 96, word: "category", meaningVi: "thể loại" },
  { id: 97, word: "cautiously", meaningVi: "thận trọng" },
  { id: 98, word: "chain", meaningVi: "chuỗi" },
  { id: 99, word: "characteristic", meaningVi: "đặc trưng" },
  { id: 100, word: "charge", meaningVi: "tính giá" },
  { id: 101, word: "check in", meaningVi: "đăng ký tại khách sạn" },
  { id: 102, word: "checkout", meaningVi: "kiểm tra" },
  { id: 103, word: "choose", meaningVi: "chọn lựa" },
  { id: 104, word: "circumstance", meaningVi: "tình hình" },
  { id: 105, word: "claim", meaningVi: "đòi lại" },
  { id: 106, word: "client", meaningVi: "khách hàng" },
  { id: 107, word: "code", meaningVi: "mật mã, luật lệ" },
  { id: 108, word: "coincide", meaningVi: "xảy ra đồng thời" },
  { id: 109, word: "collaboration", meaningVi: "hợp tác" },
  { id: 110, word: "collection", meaningVi: "bộ sưu tập" },
  { id: 111, word: "combine", meaningVi: "kết hợp" },
  { id: 112, word: "come up with", meaningVi: "đạt tới, bắt kịp" },
  { id: 113, word: "comfort", meaningVi: "an ủi" },
  { id: 114, word: "commensurate", meaningVi: "xứng với" },
  { id: 115, word: "commit", meaningVi: "cam kết" },
  { id: 116, word: "commonly", meaningVi: "thông thường" },
  { id: 117, word: "compare", meaningVi: "so sánh" },
  { id: 118, word: "compatible", meaningVi: "tương thích" },
  { id: 119, word: "compensate", meaningVi: "đền bù" },
  { id: 120, word: "competition", meaningVi: "sự cạnh tranh" },
  { id: 121, word: "compile", meaningVi: "sưu tập, biên soạn" },
  { id: 122, word: "complete", meaningVi: "hoàn thành" },
  { id: 123, word: "complication", meaningVi: "phức tạp" },
  { id: 124, word: "comprehensive", meaningVi: "bao gồm" },
  { id: 125, word: "compromise", meaningVi: "kết hợp" },
  { id: 126, word: "concentrate", meaningVi: "tập trung" },
  { id: 127, word: "concern", meaningVi: "lo ngại" },
  { id: 128, word: "conclude", meaningVi: "kết luận" },
  { id: 129, word: "condition", meaningVi: "điều kiện" },
  { id: 130, word: "conducive", meaningVi: "góp phần, dẫn đến" },
  { id: 131, word: "conduct", meaningVi: "hướng dẫn" },
  { id: 132, word: "confidence", meaningVi: "sự tự tin" },
  { id: 133, word: "confident", meaningVi: "tiếp tục" },
  { id: 134, word: "confirm", meaningVi: "xác nhận" },
  { id: 135, word: "conform", meaningVi: "tuân theo" },
  { id: 136, word: "confusion", meaningVi: "sự rắc rối" },
  { id: 137, word: "consequence", meaningVi: "hậu quả" },
  { id: 138, word: "conservative", meaningVi: "thận trọng" },
  { id: 139, word: "consider", meaningVi: "cân nhắc" },
  { id: 140, word: "constantly", meaningVi: "liên tục" },
  { id: 141, word: "constitute", meaningVi: "hình thành" },
  { id: 142, word: "consult", meaningVi: "thảo luận với" },
  { id: 143, word: "consume", meaningVi: "tiêu dùng" },
  { id: 144, word: "contact", meaningVi: "liên hệ" },
  { id: 145, word: "continue", meaningVi: "tiếp tục" },
  { id: 146, word: "contribute", meaningVi: "góp phần, dẫn đến" },
  { id: 147, word: "control", meaningVi: "kiểm soát" },
  { id: 148, word: "convenient", meaningVi: "thuận lợi" },
  { id: 149, word: "convince", meaningVi: "thuyết phục" },
  { id: 150, word: "coordinate", meaningVi: "kết hợp" },
  { id: 151, word: "courier", meaningVi: "người đưa thư" },
  { id: 152, word: "cover", meaningVi: "bao bọc" },
  { id: 153, word: "creative", meaningVi: "sáng tạo" },
  { id: 154, word: "criticism", meaningVi: "chỉ trích" },
  { id: 155, word: "crucial", meaningVi: "chủ yếu" },
  { id: 156, word: "culinary", meaningVi: "ẩm thực" },
  { id: 157, word: "currently", meaningVi: "hiện tại" },
  { id: 158, word: "customer", meaningVi: "khách hàng" },
  { id: 159, word: "daringly", meaningVi: "dũng cảm" },
  { id: 160, word: "deadline", meaningVi: "giới hạn" },
  { id: 161, word: "deal with", meaningVi: "giải quyết" },
  { id: 162, word: "debt", meaningVi: "nợ" },
  { id: 163, word: "decade", meaningVi: "năm, thập kỷ" },
  { id: 164, word: "decision", meaningVi: "quyết định" },
  { id: 165, word: "dedication", meaningVi: "sự cống hiến" },
  { id: 166, word: "deduct", meaningVi: "khấu trừ" },
  { id: 167, word: "defect", meaningVi: "lỗi" },
  { id: 168, word: "delay", meaningVi: "trì hoãn" },
  { id: 169, word: "delete", meaningVi: "xóa" },
  { id: 170, word: "delicately", meaningVi: "tế nhị" },
  { id: 171, word: "delivery", meaningVi: "phân phối" },
  { id: 172, word: "deluxe", meaningVi: "xa xỉ" },
  { id: 173, word: "demand", meaningVi: "cầu (nhu cầu)" },
  { id: 174, word: "demonstrate", meaningVi: "chứng minh" },
  { id: 175, word: "depart", meaningVi: "khởi hành" },
  { id: 176, word: "description", meaningVi: "mô tả" },
  { id: 177, word: "designate", meaningVi: "chỉ định cho" },
  { id: 178, word: "desire", meaningVi: "mong muốn" },
  { id: 179, word: "destination", meaningVi: "điểm đến" },
  { id: 180, word: "detail", meaningVi: "chi tiết" },
  { id: 181, word: "detect", meaningVi: "phát hiện" },
  { id: 182, word: "determine", meaningVi: "xác định" },
  { id: 183, word: "develop", meaningVi: "mở rộng" },
  { id: 184, word: "diagnose", meaningVi: "chẩn đoán (bệnh)" },
  { id: 185, word: "dialogue", meaningVi: "đoạn hội thoại" },
  { id: 186, word: "dimension", meaningVi: "kích thước" },
  { id: 187, word: "directory", meaningVi: "danh bạ" },
  { id: 188, word: "disappoint", meaningVi: "thất vọng" },
  { id: 189, word: "discount", meaningVi: "giảm giá" },
  { id: 190, word: "discrepancy", meaningVi: "sự khác nhau" },
  { id: 191, word: "disk", meaningVi: "ổ đĩa" },
  { id: 192, word: "disparate", meaningVi: "khác biệt" },
  { id: 193, word: "disperse", meaningVi: "lan truyền" },
  { id: 194, word: "display", meaningVi: "hiển thị" },
  { id: 195, word: "disruption", meaningVi: "sự gián đoạn" },
  { id: 196, word: "disseminate", meaningVi: "lan truyền" },
  { id: 197, word: "distinguish", meaningVi: "phân biệt" },
  { id: 198, word: "distraction", meaningVi: "làm sao nhãng" },
  { id: 199, word: "disturb", meaningVi: "làm náo động" },
  { id: 200, word: "diversity", meaningVi: "đa dạng" },
  { id: 201, word: "divide", meaningVi: "phân chia" },
  { id: 202, word: "dividend", meaningVi: "cổ phần" },
  { id: 203, word: "down payment", meaningVi: "sự trả tiền mặt" },
  { id: 204, word: "draw", meaningVi: "thu hút" },
  { id: 205, word: "due to", meaningVi: "bởi vì" },
  { id: 206, word: "duplicate", meaningVi: "bản sao" },
  { id: 207, word: "durable", meaningVi: "kéo dài" },
  { id: 208, word: "duration", meaningVi: "khoảng thời gian" },
  { id: 209, word: "economize", meaningVi: "tiết kiệm" },
  { id: 210, word: "effective", meaningVi: "hiệu quả" },
  { id: 211, word: "efficient", meaningVi: "hiệu quả" },
  { id: 212, word: "elegance", meaningVi: "sự trang nhã" },
  { id: 213, word: "element", meaningVi: "nhân tố" },
  { id: 214, word: "eligible", meaningVi: "thích hợp" },
  { id: 215, word: "embarkation", meaningVi: "lên tàu xe" },
  { id: 216, word: "emphasize", meaningVi: "nhấn mạnh" },
  { id: 217, word: "encouragement", meaningVi: "khuyến khích" },
  { id: 218, word: "engage", meaningVi: "tham gia vào" },
  { id: 219, word: "enhance", meaningVi: "nâng cao" },
  { id: 220, word: "enterprise", meaningVi: "doanh nghiệp" },
  { id: 221, word: "entertainment", meaningVi: "giải trí" },
  { id: 222, word: "entitle", meaningVi: "cho phép" },
  { id: 223, word: "equivalent", meaningVi: "tương đương với" },
  { id: 224, word: "escort", meaningVi: "người bảo vệ" },
  { id: 225, word: "essentially", meaningVi: "về bản chất" },
  { id: 226, word: "establish", meaningVi: "thành lập" },
  { id: 227, word: "estimate", meaningVi: "đánh giá" },
  { id: 228, word: "evaluate", meaningVi: "đánh giá" },
  { id: 229, word: "everyday", meaningVi: "mỗi ngày" },
  { id: 230, word: "evident", meaningVi: "rõ ràng" },
  { id: 231, word: "exact", meaningVi: "chính xác" },
  { id: 232, word: "examine", meaningVi: "kiểm tra" },
  { id: 233, word: "excite", meaningVi: "kích thích" },
  { id: 234, word: "exclude", meaningVi: "loại trừ, đuổi tống ra" },
  { id: 235, word: "excursion", meaningVi: "du lịch giá rẻ" },
  { id: 236, word: "expand", meaningVi: "mở rộng" },
  { id: 237, word: "expect", meaningVi: "mong đợi" },
  { id: 238, word: "expense", meaningVi: "chi phí" },
  { id: 239, word: "experience", meaningVi: "trải nghiệm" },
  { id: 240, word: "experiment", meaningVi: "thí nghiệm" },
  { id: 241, word: "expert", meaningVi: "chuyên gia" },
  { id: 242, word: "expiration", meaningVi: "hết hạn" },
  { id: 243, word: "explore", meaningVi: "thăm dò" },
  { id: 244, word: "expose", meaningVi: "trưng bày" },
  { id: 245, word: "express", meaningVi: "(adj) nhanh, hỏa tốc, tốc hành" },
  { id: 246, word: "extend", meaningVi: "mở rộng" },
  { id: 247, word: "facilitate", meaningVi: "làm cho thuận tiện" },
  { id: 248, word: "factor", meaningVi: "nhân tố" },
  { id: 249, word: "fad", meaningVi: "xu hướng" },
  { id: 250, word: "failure", meaningVi: "thất bại" },
  { id: 251, word: "fall to", meaningVi: "rơi vào ai (trách nhiệm)" },
  { id: 252, word: "familiar", meaningVi: "quen thuộc" },
  { id: 253, word: "fare", meaningVi: "giá vé" },
  { id: 254, word: "fashion", meaningVi: "thời trang" },
  { id: 255, word: "favor", meaningVi: "thích nhất" },
  { id: 256, word: "figure out", meaningVi: "hiểu, luận ra" },
  { id: 257, word: "file", meaningVi: "đệ trình" },
  { id: 258, word: "fill out", meaningVi: "hoàn thành" },
  { id: 259, word: "flavor", meaningVi: "hương vị" },
  { id: 260, word: "flexibly", meaningVi: "linh động" },
  { id: 261, word: "fluctuate", meaningVi: "giao động" },
  { id: 262, word: "fold", meaningVi: "gấp lại" },
  { id: 263, word: "follow up", meaningVi: "bám sát" },
  { id: 264, word: "forecast", meaningVi: "dự đoán" },
  { id: 265, word: "forget", meaningVi: "quên" },
  { id: 266, word: "frequently", meaningVi: "thường xuyên" },
  { id: 267, word: "fulfill", meaningVi: "làm đầy" },
  { id: 268, word: "function", meaningVi: "chức năng" },
  { id: 269, word: "fund", meaningVi: "quỹ" },
  { id: 270, word: "garment", meaningVi: "vải áo quần" },
  { id: 271, word: "gather", meaningVi: "thu nhập" },
  { id: 272, word: "general", meaningVi: "chung chung" },
  { id: 273, word: "generate", meaningVi: "phát ra" },
  { id: 274, word: "get in touch", meaningVi: "liên lạc với ai" },
  { id: 275, word: "get out of", meaningVi: "thoát khỏi" },
  { id: 276, word: "give up", meaningVi: "từ bỏ" },
  { id: 277, word: "glimpse", meaningVi: "lướt qua" },
  { id: 278, word: "go ahead", meaningVi: "tiến tới, cho phép" },
  { id: 279, word: "goal", meaningVi: "mục tiêu" },
  { id: 280, word: "guide", meaningVi: "người hướng dẫn" },
  { id: 281, word: "habit", meaningVi: "thói quen" },
  { id: 282, word: "hamper", meaningVi: "cản trở" },
  { id: 283, word: "hesitant", meaningVi: "dè dặt" },
  { id: 284, word: "hire", meaningVi: "thuê" },
  { id: 285, word: "hold", meaningVi: "tổ chức" },
  { id: 286, word: "housekeeper", meaningVi: "quản gia" },
  { id: 287, word: "ideally", meaningVi: "lý tưởng" },
  { id: 288, word: "identify", meaningVi: "phân biệt rõ" },
  { id: 289, word: "ignore", meaningVi: "phớt lờ" },
  { id: 290, word: "illuminate", meaningVi: "làm trắng sáng" },
  { id: 291, word: "impact", meaningVi: "ảnh hưởng" },
  { id: 292, word: "imply", meaningVi: "hàm ý" },
  { id: 293, word: "impose", meaningVi: "đánh thuế" },
  { id: 294, word: "impress", meaningVi: "ấn tượng" },
  { id: 295, word: "in charge of", meaningVi: "phụ trách, đứng đầu" },
  { id: 296, word: "inconsiderately", meaningVi: "không lịch sự" },
  { id: 297, word: "incorporate", meaningVi: "kết hợp" },
  { id: 298, word: "incur", meaningVi: "hứng chịu" },
  { id: 299, word: "in-depth", meaningVi: "sâu sắc" },
  { id: 300, word: "indicator", meaningVi: "dấu hiệu" },
  { id: 301, word: "individual", meaningVi: "cá nhân" },
  { id: 302, word: "influence", meaningVi: "ảnh hưởng" },
  { id: 303, word: "influx", meaningVi: "dòng chảy vào" },
  { id: 304, word: "ingredient", meaningVi: "thành phần" },
  { id: 305, word: "initiative", meaningVi: "sáng kiến" },
  { id: 306, word: "inspect", meaningVi: "kiểm tra kỹ lưỡng" },
  { id: 307, word: "inspiration", meaningVi: "truyền cảm hứng" },
  { id: 308, word: "instinct", meaningVi: "bản năng" },
  { id: 309, word: "instrument", meaningVi: "thiết bị" },
  { id: 310, word: "integral", meaningVi: "phần không thể thiếu" },
  { id: 311, word: "intend", meaningVi: "có ý định" },
  { id: 312, word: "interaction", meaningVi: "phản ứng phụ" },
  { id: 313, word: "inventory", meaningVi: "hàng tồn kho" },
  { id: 314, word: "invest", meaningVi: "đầu tư" },
  { id: 315, word: "investigate", meaningVi: "điều tra rõ ràng" },
  { id: 316, word: "irritate", meaningVi: "làm nhức nhối" },
  { id: 317, word: "item", meaningVi: "món (ghi trong đơn hàng)" },
  { id: 318, word: "itinerary", meaningVi: "lịch trình" },
  { id: 319, word: "joint", meaningVi: "nối lại" },
  { id: 320, word: "judge", meaningVi: "đánh giá" },
  { id: 321, word: "keep up with", meaningVi: "theo kịp" },
  { id: 322, word: "layout", meaningVi: "bố cục trang giấy" },
  { id: 323, word: "lead time", meaningVi: "thời gian thực hiện" },
  { id: 324, word: "lease", meaningVi: "hợp đồng thuê" },
  { id: 325, word: "leisure", meaningVi: "thời gian rỗi" },
  { id: 326, word: "lengthy", meaningVi: "kéo dài" },
  { id: 327, word: "level", meaningVi: "mức độ" },
  { id: 328, word: "liability", meaningVi: "nợ" },
  { id: 329, word: "license", meaningVi: "giấy phép" },
  { id: 330, word: "limit", meaningVi: "hạn chế" },
  { id: 331, word: "link", meaningVi: "liên kết" },
  { id: 332, word: "list", meaningVi: "danh sách" },
  { id: 333, word: "lobby", meaningVi: "hành lang" },
  { id: 334, word: "location", meaningVi: "vị trí" },
  { id: 335, word: "lock into", meaningVi: "gắn liền với cái gì đó" },
  { id: 336, word: "logical", meaningVi: "hợp lý, logic" },
  { id: 337, word: "long-term", meaningVi: "dài kỳ" },
  { id: 338, word: "look forward to", meaningVi: "trông chờ" },
  { id: 339, word: "look to", meaningVi: "trông cậy vào" },
  { id: 340, word: "look up to", meaningVi: "kính trọng" },
  { id: 341, word: "loyal", meaningVi: "trung thành" },
  { id: 342, word: "made of", meaningVi: "được làm từ" },
  { id: 343, word: "maintain", meaningVi: "duy trì" },
  { id: 344, word: "majority", meaningVi: "nhiều" },
  { id: 345, word: "manage", meaningVi: "xoay xở" },
  { id: 346, word: "mandatory", meaningVi: "có tính bắt buộc" },
  { id: 347, word: "market", meaningVi: "tạo thị trường" },
  { id: 348, word: "match", meaningVi: "phù hợp" },
  { id: 349, word: "matter", meaningVi: "vấn đề" },
  { id: 350, word: "mention", meaningVi: "đề cập" },
  { id: 351, word: "mentor", meaningVi: "người kỳ cựu" },
  { id: 352, word: "merchandise", meaningVi: "hàng hóa" },
  { id: 353, word: "merit", meaningVi: "công lao" },
  { id: 354, word: "method", meaningVi: "phương pháp" },
  { id: 355, word: "minimize", meaningVi: "làm nhỏ đi" },
  { id: 356, word: "mission", meaningVi: "nhiệm vụ" },
  { id: 357, word: "mistake", meaningVi: "lỗi lầm" },
  { id: 358, word: "mix", meaningVi: "trộn" },
  { id: 359, word: "mix-up", meaningVi: "sự lộn xộn" },
  { id: 360, word: "monitor", meaningVi: "quản lý" },
  { id: 361, word: "mortgage", meaningVi: "thế chấp" },
  { id: 362, word: "move up", meaningVi: "thăng tiến" },
  { id: 363, word: "multiple", meaningVi: "nhiều" },
  { id: 364, word: "narrow", meaningVi: "rút gọn" },
  { id: 365, word: "negotiate", meaningVi: "đàm phán" },
  { id: 366, word: "nervously", meaningVi: "lo lắng" },
  { id: 367, word: "network", meaningVi: "mạng lưới" },
  { id: 368, word: "notify", meaningVi: "báo cáo" },
  { id: 369, word: "obligate", meaningVi: "bắt buộc" },
  { id: 370, word: "obtain", meaningVi: "đạt được" },
  { id: 371, word: "obviously", meaningVi: "rõ ràng" },
  { id: 372, word: "occupy", meaningVi: "chiếm chỗ" },
  { id: 373, word: "occur", meaningVi: "xảy ra" },
  { id: 374, word: "offer", meaningVi: "sự lựa chọn" },
  { id: 375, word: "offset", meaningVi: "bù lại" },
  { id: 376, word: "on hand", meaningVi: "có sẵn" },
  { id: 377, word: "on track", meaningVi: "theo kế hoạch" },
  { id: 378, word: "open to", meaningVi: "đón nhận" },
  { id: 379, word: "operate", meaningVi: "vận hành" },
  { id: 380, word: "opt", meaningVi: "lựa chọn" },
  { id: 381, word: "option", meaningVi: "lựa chọn" },
  { id: 382, word: "optional", meaningVi: "lựa chọn" },
  { id: 383, word: "order", meaningVi: "đơn hàng" },
  { id: 384, word: "out of", meaningVi: "đã hết" },
  { id: 385, word: "outdated", meaningVi: "lỗi thời" },
  { id: 386, word: "outlet", meaningVi: "đại lý" },
  { id: 387, word: "outstanding", meaningVi: "chưa trả (nợ)" },
  { id: 388, word: "overall", meaningVi: "toàn bộ" },
  { id: 389, word: "overcrowded", meaningVi: "quá đông" },
  { id: 390, word: "overview", meaningVi: "tóm tắt, nhìn nhanh" },
  { id: 391, word: "owe", meaningVi: "nợ" },
  { id: 392, word: "party", meaningVi: "bên (đối tác), tổ chức" },
  { id: 393, word: "patron", meaningVi: "khách quen" },
  { id: 394, word: "penalty", meaningVi: "tiền phạt" },
  { id: 395, word: "perceptive", meaningVi: "nhận thức" },
  { id: 396, word: "perform", meaningVi: "diễn kịch" },
  { id: 397, word: "periodically", meaningVi: "định kỳ" },
  { id: 398, word: "permit", meaningVi: "cho phép" },
  { id: 399, word: "personnel", meaningVi: "nhóm người làm" },
  { id: 400, word: "perspective", meaningVi: "triển vọng" },
  { id: 401, word: "persuasion", meaningVi: "thuyết phục" },
  { id: 402, word: "pertinent", meaningVi: "tương ứng" },
  { id: 403, word: "petition", meaningVi: "kiến nghị" },
  { id: 404, word: "physically", meaningVi: "luật tự nhiên" },
  { id: 405, word: "pick up", meaningVi: "nhặt" },
  { id: 406, word: "plan", meaningVi: "lên kế hoạch" },
  { id: 407, word: "policy", meaningVi: "chính sách" },
  { id: 408, word: "popularity", meaningVi: "phổ biến" },
  { id: 409, word: "portfolio", meaningVi: "danh mục đầu tư" },
  { id: 410, word: "portion", meaningVi: "bộ phận" },
  { id: 411, word: "position", meaningVi: "vị trí" },
  { id: 412, word: "potential", meaningVi: "tiềm năng" },
  { id: 413, word: "practice", meaningVi: "luyện tập" },
  { id: 414, word: "preclude", meaningVi: "ngăn cản" },
  { id: 415, word: "predict", meaningVi: "dự đoán" },
  { id: 416, word: "prefer", meaningVi: "thích hơn" },
  { id: 417, word: "preparation", meaningVi: "chuẩn bị" },
  { id: 418, word: "prerequisite", meaningVi: "điều kiện tiên quyết" },
  { id: 419, word: "present", meaningVi: "đưa ra" },
  { id: 420, word: "prevent", meaningVi: "ngăn chặn" },
  { id: 421, word: "primarily", meaningVi: "chủ yếu" },
  { id: 422, word: "priority", meaningVi: "ưu tiên hàng đầu" },
  { id: 423, word: "proactive", meaningVi: "chủ động" },
  { id: 424, word: "procedure", meaningVi: "quá trình" },
  { id: 425, word: "process", meaningVi: "xử lý" },
  { id: 426, word: "productive", meaningVi: "có năng suất" },
  { id: 427, word: "profession", meaningVi: "nghề nghiệp" },
  { id: 428, word: "profile", meaningVi: "sơ lược về tiểu sử" },
  { id: 429, word: "profitably", meaningVi: "lợi nhuận" },
  { id: 430, word: "progress", meaningVi: "bước tiến tương lai" },
  { id: 431, word: "prohibit", meaningVi: "ngăn cấm" },
  { id: 432, word: "project", meaningVi: "kế hoạch" },
  { id: 433, word: "promise", meaningVi: "cam kết" },
  { id: 434, word: "promote", meaningVi: "thúc đẩy" },
  { id: 435, word: "promptly", meaningVi: "nhanh chóng" },
  { id: 436, word: "proof", meaningVi: "chứng cớ" },
  { id: 437, word: "prospective", meaningVi: "tiềm năng" },
  { id: 438, word: "protect", meaningVi: "bảo vệ" },
  { id: 439, word: "provider", meaningVi: "nhà cung cấp" },
  { id: 440, word: "provision", meaningVi: "điều khoản" },
  { id: 441, word: "proximity", meaningVi: "gần" },
  { id: 442, word: "pull out", meaningVi: "kéo đổ" },
  { id: 443, word: "punctually", meaningVi: "đúng giờ" },
  { id: 444, word: "qualification", meaningVi: "phẩm chất, năng lực" },
  { id: 445, word: "quality", meaningVi: "phẩm chất, năng lực" },
  { id: 446, word: "quote", meaningVi: "tính giá" },
  { id: 447, word: "raise", meaningVi: "nâng lên" },
  { id: 448, word: "randomly", meaningVi: "ngẫu nhiên" },
  { id: 449, word: "range", meaningVi: "thể loại" },
  { id: 450, word: "rate", meaningVi: "mức giá" },
  { id: 451, word: "ready for", meaningVi: "sẵn sàng cho" },
  { id: 452, word: "realistic", meaningVi: "thực tế" },
  { id: 453, word: "reason", meaningVi: "lý do" },
  { id: 454, word: "recognition", meaningVi: "công nhận" },
  { id: 455, word: "recommendation", meaningVi: "lời khuyên" },
  { id: 456, word: "reconcile", meaningVi: "giải hòa" },
  { id: 457, word: "record", meaningVi: "báo cáo" },
  { id: 458, word: "recruit", meaningVi: "tuyển dụng" },
  { id: 459, word: "rectify", meaningVi: "sửa sai" },
  { id: 460, word: "recur", meaningVi: "trở lại" },
  { id: 461, word: "reduction", meaningVi: "giảm giá" },
  { id: 462, word: "refer", meaningVi: "hướng dẫn tới" },
  { id: 463, word: "reflection", meaningVi: "phản ánh" },
  { id: 464, word: "refund", meaningVi: "sự trả lại" },
  { id: 465, word: "regardless", meaningVi: "bất chấp" },
  { id: 466, word: "register", meaningVi: "ghi nhận, vào sổ" },
  { id: 467, word: "regularly", meaningVi: "định kỳ" },
  { id: 468, word: "regulate", meaningVi: "quản lý" },
  { id: 469, word: "rehearse", meaningVi: "luyện tập" },
  { id: 470, word: "reinforce", meaningVi: "củng cố" },
  { id: 471, word: "reject", meaningVi: "loại bỏ" },
  { id: 472, word: "relatively", meaningVi: "hầu như" },
  { id: 473, word: "relaxation", meaningVi: "sự thư giãn" },
  { id: 474, word: "release", meaningVi: "phát hành" },
  { id: 475, word: "relinquish", meaningVi: "đầu hàng, từ bỏ" },
  { id: 476, word: "rely", meaningVi: "dựa vào" },
  { id: 477, word: "remainder", meaningVi: "phần còn lại" },
  { id: 478, word: "remember", meaningVi: "nhớ lại" },
  { id: 479, word: "remind", meaningVi: "nhắc nhở" },
  { id: 480, word: "remote", meaningVi: "xa xôi" },
  { id: 481, word: "repel", meaningVi: "ngăn ngừa" },
  { id: 482, word: "replace", meaningVi: "thay thế" },
  { id: 483, word: "report", meaningVi: "báo cáo, bản báo cáo" },
  { id: 484, word: "representation", meaningVi: "đại diện" },
  { id: 485, word: "reputation", meaningVi: "danh tiếng" },
  { id: 486, word: "require", meaningVi: "yêu cầu" },
  { id: 487, word: "research", meaningVi: "nghiên cứu" },
  { id: 488, word: "reservation", meaningVi: "sự đặt chỗ" },
  { id: 489, word: "resolve", meaningVi: "giải quyết vấn đề" },
  { id: 490, word: "resource", meaningVi: "tài nguyên" },
  { id: 491, word: "respond", meaningVi: "trả lời" },
  { id: 492, word: "responsibility", meaningVi: "trách nhiệm" },
  { id: 493, word: "restore", meaningVi: "khôi phục lại" },
  { id: 494, word: "restricted", meaningVi: "hạn chế" },
  { id: 495, word: "result", meaningVi: "kết quả" },
  { id: 496, word: "retire", meaningVi: "nghỉ hưu" },
  { id: 497, word: "return", meaningVi: "trở lại" },
  { id: 498, word: "review", meaningVi: "đánh giá" },
  { id: 499, word: "revise", meaningVi: "sửa lại" },
  { id: 500, word: "revolution", meaningVi: "cuộc cách mạng" },
  { id: 501, word: "risk", meaningVi: "mạo hiểm" },
  { id: 502, word: "run", meaningVi: "chạy" },
  { id: 503, word: "salary", meaningVi: "lương" },
  { id: 504, word: "sample", meaningVi: "mẫu" },
  { id: 505, word: "satisfaction", meaningVi: "làm ai hài lòng" },
  { id: 506, word: "scan", meaningVi: "quét" },
  { id: 507, word: "schedule", meaningVi: "lên lịch trình" },
  { id: 508, word: "scrutiny", meaningVi: "kiểm tra kỹ lưỡng" },
  { id: 509, word: "search", meaningVi: "tìm kiếm" },
  { id: 510, word: "secure", meaningVi: "chiếm chỗ" },
  { id: 511, word: "select", meaningVi: "chọn" },
  { id: 512, word: "sell out", meaningVi: "bán hết" },
  { id: 513, word: "sense", meaningVi: "giác quan" },
  { id: 514, word: "separately", meaningVi: "phân chia" },
  { id: 515, word: "serious", meaningVi: "trầm trọng" },
  { id: 516, word: "service", meaningVi: "dịch vụ" },
  { id: 517, word: "session", meaningVi: "buổi họp" },
  { id: 518, word: "set up", meaningVi: "cài đặt" },
  { id: 519, word: "settle", meaningVi: "trả (tiền), chọn" },
  { id: 520, word: "sharp", meaningVi: "làm nhọn" },
  { id: 521, word: "ship", meaningVi: "chuyển hàng" },
  { id: 522, word: "shut down", meaningVi: "tắt máy" },
  { id: 523, word: "signature", meaningVi: "chữ ký" },
  { id: 524, word: "significant", meaningVi: "quan trọng" },
  { id: 525, word: "site", meaningVi: "địa điểm" },
  { id: 526, word: "situation", meaningVi: "tình hình" },
  { id: 527, word: "skill", meaningVi: "kỹ năng" },
  { id: 528, word: "smooth", meaningVi: "mềm mại" },
  { id: 529, word: "software", meaningVi: "phần mềm" },
  { id: 530, word: "solve", meaningVi: "giải quyết vấn đề" },
  { id: 531, word: "source", meaningVi: "nguồn (tài liệu...)" },
  { id: 532, word: "specialize", meaningVi: "chuyên gia" },
  { id: 533, word: "specific", meaningVi: "đặc biệt" },
  { id: 534, word: "spectrum", meaningVi: "bao gồm" },
  { id: 535, word: "spouse", meaningVi: "vợ, chồng" },
  { id: 536, word: "stage", meaningVi: "tổ chức" },
  { id: 537, word: "statement", meaningVi: "hóa đơn" },
  { id: 538, word: "stationery", meaningVi: "đồ dùng văn phòng" },
  { id: 539, word: "stay on top of", meaningVi: "bắt kịp thời đại" },
  { id: 540, word: "stock", meaningVi: "cổ phiếu, kho hàng" },
  { id: 541, word: "store", meaningVi: "cửa hàng" },
  { id: 542, word: "strategy", meaningVi: "chiến lược" },
  { id: 543, word: "strictly", meaningVi: "chặt chẽ" },
  { id: 544, word: "strong", meaningVi: "bền vững" },
  { id: 545, word: "subject to", meaningVi: "chịu sự quản lý của" },
  { id: 546, word: "subjective", meaningVi: "chủ quan" },
  { id: 547, word: "submit", meaningVi: "đệ trình" },
  { id: 548, word: "subscribe", meaningVi: "đăng ký nhận báo" },
  { id: 549, word: "substantially", meaningVi: "lớn" },
  { id: 550, word: "substitution", meaningVi: "thay thế" },
  { id: 551, word: "subtract", meaningVi: "trừ" },
  { id: 552, word: "success", meaningVi: "thành công" },
  { id: 553, word: "successive", meaningVi: "kế tiếp" },
  { id: 554, word: "sufficiently", meaningVi: "hiệu quả" },
  { id: 555, word: "suggestion", meaningVi: "đề nghị" },
  { id: 556, word: "suit", meaningVi: "phù hợp" },
  { id: 557, word: "supervisor", meaningVi: "người giám sát" },
  { id: 558, word: "supply", meaningVi: "cung cấp" },
  { id: 559, word: "system", meaningVi: "hệ thống" },
  { id: 560, word: "systematically", meaningVi: "theo hệ thống" },
  { id: 561, word: "take back", meaningVi: "trả lại" },
  { id: 562, word: "take out", meaningVi: "rút hết (tiền)" },
  { id: 563, word: "take part in", meaningVi: "tham gia" },
  { id: 564, word: "target", meaningVi: "mục tiêu" },
  { id: 565, word: "taste", meaningVi: "khẩu vị" },
  { id: 566, word: "technically", meaningVi: "về mặt kỹ thuật" },
  { id: 567, word: "tedious", meaningVi: "tẻ nhạt" },
  { id: 568, word: "tempt", meaningVi: "bị kích thích" },
  { id: 569, word: "terms", meaningVi: "điều khoản" },
  { id: 570, word: "theme", meaningVi: "giao diện" },
  { id: 571, word: "thorough", meaningVi: "toàn diện" },
  { id: 572, word: "thrill", meaningVi: "gây nên sự thích thú" },
  { id: 573, word: "throw out", meaningVi: "vứt bỏ" },
  { id: 574, word: "tier", meaningVi: "loại" },
  { id: 575, word: "time-consuming", meaningVi: "tốn thời gian" },
  { id: 576, word: "training", meaningVi: "đào tạo" },
  { id: 577, word: "transaction", meaningVi: "giao dịch" },
  { id: 578, word: "translation", meaningVi: "sự dịch thuật" },
  { id: 579, word: "trend", meaningVi: "xu hướng" },
  { id: 580, word: "turnover", meaningVi: "vòng quay hàng hóa" },
  { id: 581, word: "typically", meaningVi: "điển hình" },
  { id: 582, word: "uniformly", meaningVi: "giống nhau" },
  { id: 583, word: "update", meaningVi: "cập nhật" },
  { id: 584, word: "urge", meaningVi: "thúc giục" },
  { id: 585, word: "usually", meaningVi: "thông thường" },
  { id: 586, word: "valid", meaningVi: "hợp lệ" },
  { id: 587, word: "value", meaningVi: "giá trị" },
  { id: 588, word: "variety", meaningVi: "nhiều loại" },
  { id: 589, word: "verbally", meaningVi: "bằng miệng" },
  { id: 590, word: "verify", meaningVi: "làm rõ" },
  { id: 591, word: "vested", meaningVi: "được trao cho" },
  { id: 592, word: "volunteer", meaningVi: "tình nguyện" },
  { id: 593, word: "wage", meaningVi: "lương" },
  { id: 594, word: "warning", meaningVi: "cảnh báo" },
  { id: 595, word: "waste", meaningVi: "lãng phí" },
  { id: 596, word: "weakly", meaningVi: "hàng tuần" },
  { id: 597, word: "wisely", meaningVi: "thông minh" },
  { id: 598, word: "withhold", meaningVi: "giữ lại" },
  { id: 599, word: "wrinkle", meaningVi: "vết nhăn (quần áo)" },
  { id: 600, word: "yield", meaningVi: "lợi nhuận" },
];
